#ifndef PINS_H
#define PINS_H

#define MOTOR_LF_PIN 2
#define MOTOR_LB_PIN 3
#define MOTOR_RF_PIN 4
#define MOTOR_RB_PIN 5
#define MOTOR_LPWM_PIN 9
#define MOTOR_RPWM_PIN 10

#define ULTRASONIC_FRONT_TRIG_PIN 6
#define ULTRASONIC_FRONT_ECHO_PIN 7
#define ULTRASONIC_BACK_TRIG_PIN 8
#define ULTRASONIC_BACK_ECHO_PIN 11
#define ULTRASONIC_LEFT_TRIG_PIN 12
#define ULTRASONIC_LEFT_ECHO_PIN 13
#define ULTRASONIC_RIGHT_TRIG_PIN A0
#define ULTRASONIC_RIGHT_ECHO_PIN A1

#define RED_LED_PIN LED_BUILTIN
#define BUZZER_PIN A2

#endif